name: wind-externalities
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.8
    - flake8=3.8.3
    - snakemake-minimal=6.0.5
    - jupyter=1.0
    - pandas=1.3
    - matplotlib=3.4
    - pip
    - pip:
        - simpledbf
