name: default_environment
channels:
    - conda-forge
    - bioconda
dependencies:
    - snakemake-minimal=6.5.3
    - python=3.8
    - numpy=1.20.2
    - scipy=1.6.2
    - pandas=1.2.3
    - gdal=3.2.1
    - libgdal=3.2.1
    - fiona=1.8.18
    - rasterio=1.2.1
    - rasterstats=0.14.0
    - geos=3.9.1
    - geopandas=0.9.0
    - netcdf4=1.5.6
    - xarray=0.17.0
    - rioxarray=0.9.0
    - matplotlib=3.3.0
    - seaborn=0.11.2
    - glaes=1.2.1
